### ISSUE TITLE
wannier90 hr_dat conversion

### ISSUE THREAD

**Issue by chrisewolf** [w2dynamics/w2dynamics#1]
Hi guys,

just a quick question. Reading through the paper I found that w2dynamics has an interface for wannier90 hamiltonians (would be very neat as I do not have Wien2k but VASP); but I do not understand how that feature works. Maybe someone could outline it briefly or point me to the part of the code that does the conversion (input.py does mention w90 sometimes but not in the context of reading the hamiltonian as far as I can see)!

Thanks in advance and with best regards from Spain,
Chris

**Comment by CaptainSifff** [comment]
Dear Chris,
here's the answer:
"Hi, 
w2dynamics expects an H(k) as input. After you have the wannier90_hr.dat file containing the H(r), you should perform a plain Fourier transform and generate the H(k) for all k-points in the BZ, in the format

Nk   dimension_of_Hk   dimension_of_Hk
k1x    k1y   k1z
ReH(k1)_11 ImH(k1)_11 ReH(k1)_12 ImH(k1)_12 …
ReH(k1)_21 ImH(k1)_21 …..
k2x    k2y   k2z
ReH(k2)_11 ImH(k2)_11 ReH(k2)_12 ImH(k2)_12 …
ReH(k2)_21 ImH(k2)_21 …..
k3x    k3y   k3z
ReH(k3)_11 ImH(k3)_11 ReH(k3)_12 ImH(k3)_12 …
ReH(k3)_21 ImH(k3)_21 …..
…

In wien2wannier there should be a tool for doing the plain Fourier transform, that is however not contained in vasp2wannier, but since it is really the plain Fourier transform, we decided to leave it to the users.”

**Comment by chrisewolf** [comment]
Dear CaptainSifff,

Thank you for your reply. Now reading the section in the paper again it is actually well described with a reference to wien2wannier - I guess I was reading over it too quickly!

Thanks a lot!
Chris

**Comment by CaptainSifff** [comment]
close this.
